xxx

diff --git a/.github/workflows/release.yml b/.github/workflows/release.yml
--- a/.github/workflows/release.yml
+++ b/.github/workflows/release.yml
@@ -56,13 +56,12 @@ jobs:
               blender_version=$(python -c "import toml; print(toml.load('$file')['blender_version_min'])")
               zipname="${id}_${version}-blender-${blender_version}.zip"
               
-              # (cd "$dir" && zip -r "../$zipname" . -x "__pycache__/*" "*.pyc") || (echo "Failed to create zip: $zipname" && exit 1)
-              (cd "$dir" && zip -r "./$zipname" . -x "__pycache__/*" "*.pyc") || (echo "Failed to create zip: $zipname" && exit 1)
+              (cd "$dir" && zip -r "../$zipname" . -x "__pycache__/*" "*.pyc") || (echo "Failed to create zip: $zipname" && exit 1)
               touched_manifests=1
 
               echo "zipname variable is: $zipname"
               echo "Archiving directory: $dir"
-              ls -la "$dir"
+              ls -la "$dir/.."
             fi
           done
 
