xxx

diff --git a/.github/workflows/release.yml b/.github/workflows/release.yml
--- a/.github/workflows/release.yml
+++ b/.github/workflows/release.yml
@@ -56,7 +56,7 @@ jobs:
               blender_version=$(python -c "import toml; print(toml.load('$file')['blender_version_min'])")
               zipname="${id}_${version}-blender-${blender_version}.zip"
               
-              (cd "$dir" && zip -r "../$zipname" . -x "__pycache__/*" "*.pyc") || (echo "Failed to create zip: $zipname" && exit 1)
+              (cd "$dir" && zip -r "../$zipname" . -x "__pycache__/*" "*.pyc" ".vscode/*") || (echo "Failed to create zip: $zipname" && exit 1)
               touched_manifests=1
 
               zip_paths+="$dir/../$zipname,"
@@ -76,7 +76,8 @@ jobs:
             exit 0
           else
             echo "created=true" >> $GITHUB_OUTPUT
-            echo "release_name=$zipname" >> $GITHUB_OUTPUT
+            release_name = "Release ${id}_${version}-blender-${blender_version}"
+            echo "release_name=$release_name" >> $GITHUB_OUTPUT
           fi
         fi
 
