xxx

diff --git a/.github/workflows/release.yml b/.github/workflows/release.yml
--- a/.github/workflows/release.yml
+++ b/.github/workflows/release.yml
@@ -55,7 +55,7 @@ jobs:
               version=$(python -c "import toml; print(toml.load('$file')['version'])")
               blender_version=$(python -c "import toml; print(toml.load('$file')['blender_version_min'])")
               zipname="${id}_${version}-blender-${blender_version}.zip"
-              (cd "$dir" && zip -r "../$zipname" .) || (echo "Failed to create zip: $zipname" && exit 1)
+              (cd "$dir" && zip -r "../$zipname" . -x "__pycache__/*" "*.pyc") || (echo "Failed to create zip: $zipname" && exit 1)
               touched_manifests=1
             fi
           done
